version: "3.3"
services:
  splunk:
    image: splunk/splunk:8.0-debian
    container_name: splunk-1
    ports:
      - "8000:8000"
    environment:
      SPLUNK_START_ARGS: "--accept-license"
      SPLUNK_PASSWORD: "changeme1"
      SPLUNK_VERSION: "8.0-debian"
    volumes:
      - ./password_manager:/opt/splunk/etc/apps/password_manager
